# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _graphene
else:
    import _graphene

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _graphene.delete_SwigPyIterator

    def value(self):
        return _graphene.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _graphene.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _graphene.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _graphene.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _graphene.SwigPyIterator_equal(self, x)

    def copy(self):
        return _graphene.SwigPyIterator_copy(self)

    def next(self):
        return _graphene.SwigPyIterator_next(self)

    def __next__(self):
        return _graphene.SwigPyIterator___next__(self)

    def previous(self):
        return _graphene.SwigPyIterator_previous(self)

    def advance(self, n):
        return _graphene.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _graphene.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _graphene.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _graphene.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _graphene.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _graphene.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _graphene.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _graphene:
_graphene.SwigPyIterator_swigregister(SwigPyIterator)

class Vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _graphene.Vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _graphene.Vector___nonzero__(self)

    def __bool__(self):
        return _graphene.Vector___bool__(self)

    def __len__(self):
        return _graphene.Vector___len__(self)

    def __getslice__(self, i, j):
        return _graphene.Vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _graphene.Vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _graphene.Vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _graphene.Vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _graphene.Vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _graphene.Vector___setitem__(self, *args)

    def pop(self):
        return _graphene.Vector_pop(self)

    def append(self, x):
        return _graphene.Vector_append(self, x)

    def empty(self):
        return _graphene.Vector_empty(self)

    def size(self):
        return _graphene.Vector_size(self)

    def swap(self, v):
        return _graphene.Vector_swap(self, v)

    def begin(self):
        return _graphene.Vector_begin(self)

    def end(self):
        return _graphene.Vector_end(self)

    def rbegin(self):
        return _graphene.Vector_rbegin(self)

    def rend(self):
        return _graphene.Vector_rend(self)

    def clear(self):
        return _graphene.Vector_clear(self)

    def get_allocator(self):
        return _graphene.Vector_get_allocator(self)

    def pop_back(self):
        return _graphene.Vector_pop_back(self)

    def erase(self, *args):
        return _graphene.Vector_erase(self, *args)

    def __init__(self, *args):
        _graphene.Vector_swiginit(self, _graphene.new_Vector(*args))

    def push_back(self, x):
        return _graphene.Vector_push_back(self, x)

    def front(self):
        return _graphene.Vector_front(self)

    def back(self):
        return _graphene.Vector_back(self)

    def assign(self, n, x):
        return _graphene.Vector_assign(self, n, x)

    def resize(self, *args):
        return _graphene.Vector_resize(self, *args)

    def insert(self, *args):
        return _graphene.Vector_insert(self, *args)

    def reserve(self, n):
        return _graphene.Vector_reserve(self, n)

    def capacity(self):
        return _graphene.Vector_capacity(self)
    __swig_destroy__ = _graphene.delete_Vector

# Register Vector in _graphene:
_graphene.Vector_swigregister(Vector)

class NestedVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _graphene.NestedVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _graphene.NestedVector___nonzero__(self)

    def __bool__(self):
        return _graphene.NestedVector___bool__(self)

    def __len__(self):
        return _graphene.NestedVector___len__(self)

    def __getslice__(self, i, j):
        return _graphene.NestedVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _graphene.NestedVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _graphene.NestedVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _graphene.NestedVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _graphene.NestedVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _graphene.NestedVector___setitem__(self, *args)

    def pop(self):
        return _graphene.NestedVector_pop(self)

    def append(self, x):
        return _graphene.NestedVector_append(self, x)

    def empty(self):
        return _graphene.NestedVector_empty(self)

    def size(self):
        return _graphene.NestedVector_size(self)

    def swap(self, v):
        return _graphene.NestedVector_swap(self, v)

    def begin(self):
        return _graphene.NestedVector_begin(self)

    def end(self):
        return _graphene.NestedVector_end(self)

    def rbegin(self):
        return _graphene.NestedVector_rbegin(self)

    def rend(self):
        return _graphene.NestedVector_rend(self)

    def clear(self):
        return _graphene.NestedVector_clear(self)

    def get_allocator(self):
        return _graphene.NestedVector_get_allocator(self)

    def pop_back(self):
        return _graphene.NestedVector_pop_back(self)

    def erase(self, *args):
        return _graphene.NestedVector_erase(self, *args)

    def __init__(self, *args):
        _graphene.NestedVector_swiginit(self, _graphene.new_NestedVector(*args))

    def push_back(self, x):
        return _graphene.NestedVector_push_back(self, x)

    def front(self):
        return _graphene.NestedVector_front(self)

    def back(self):
        return _graphene.NestedVector_back(self)

    def assign(self, n, x):
        return _graphene.NestedVector_assign(self, n, x)

    def resize(self, *args):
        return _graphene.NestedVector_resize(self, *args)

    def insert(self, *args):
        return _graphene.NestedVector_insert(self, *args)

    def reserve(self, n):
        return _graphene.NestedVector_reserve(self, n)

    def capacity(self):
        return _graphene.NestedVector_capacity(self)
    __swig_destroy__ = _graphene.delete_NestedVector

# Register NestedVector in _graphene:
_graphene.NestedVector_swigregister(NestedVector)


def GaussianElimination(a):
    vect = NestedVector(a)
    return _graphene.GaussianElimination(vect)

class Fraction(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    numerator = property(_graphene.Fraction_numerator_get, _graphene.Fraction_numerator_set)
    denominator = property(_graphene.Fraction_denominator_get, _graphene.Fraction_denominator_set)
    temp = property(_graphene.Fraction_temp_get, _graphene.Fraction_temp_set)

    def __init__(self, *args):
        if len(args) == 1 and '/' in args[0]:
            args = tuple(args[0].split('/'))
        _graphene.Fraction_swiginit(self, _graphene.new_Fraction(*args))

    @staticmethod
    def remove_zero(e):
        return _graphene.Fraction_remove_zero(e)

    def __add__(self, *args):
        return _graphene.Fraction___add__(self, *args)

    def __nonzero__(self):
        return _graphene.Fraction___nonzero__(self)
    __bool__ = __nonzero__



    def __eq__(self, *args):
        return _graphene.Fraction___eq__(self, *args)

    def __ne__(self, *args):
        return _graphene.Fraction___ne__(self, *args)

    def __lt__(self, *args):
        return _graphene.Fraction___lt__(self, *args)

    def __gt__(self, *args):
        return _graphene.Fraction___gt__(self, *args)

    def __sub__(self, *args):
        return _graphene.Fraction___sub__(self, *args)

    def __mul__(self, *args):
        return _graphene.Fraction___mul__(self, *args)

    def __iadd__(self, *args):
        return _graphene.Fraction___iadd__(self, *args)

    def __isub__(self, *args):
        return _graphene.Fraction___isub__(self, *args)

    def __truediv__(self, *args):
        return _graphene.Fraction___truediv__(self, *args)
    __div__ = __truediv__



    def abso(self):
        return _graphene.Fraction_abso(self)

    def get_num(self):
        return _graphene.Fraction_get_num(self)

    def get_den(self):
        return _graphene.Fraction_get_den(self)

    def toInt(self):
        return _graphene.Fraction_toInt(self)

    def reduce_fraction(self, obj):
        return _graphene.Fraction_reduce_fraction(self, obj)

    def __str__(self):
        return _graphene.Fraction___str__(self)
    
    __repr__ = __str__
    
    __swig_destroy__ = _graphene.delete_Fraction

# Register Fraction in _graphene:
_graphene.Fraction_swigregister(Fraction)
cvar = _graphene.cvar

def Fraction_remove_zero(e):
    return _graphene.Fraction_remove_zero(e)



